analytics: {}
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.682436
  rhythmicContrast: 0.696875
  saturation: 1
cta: {}
layout_spectrum: 0
name: VN2015
opengraph: {}
purpose: {}
typography_spectrum: 0
